## Import Libraries

In [57]:
import os
import pandas as pd
import geopandas as gpd
from zipfile import ZipFile

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

## Define File Paths

In [58]:
DATA_DIR = Path("../data/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

## Define Database Connection

In [59]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

## Masking Environment Variables

In [60]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

## Define Engine

In [61]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

## Test Connection

In [62]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

## Test PostGIS Extension

In [63]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

## Citibike to PstgreSQL

### Reading The Data

In [64]:
citibike_df = pd.read_csv(citibike_path)
citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [65]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

### Cleaning The Data

In [66]:
citibike_df['started_at'] = pd.to_datetime(
    citibike_df['started_at'],
    errors='coerce'
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df['ended_at'],
    errors='coerce'
)

In [67]:
citibike_df['ride_date'] = citibike_df['started_at'].dt.date

citibike_df['ride_date'] = pd.to_datetime(
    citibike_df['ride_date'],
    errors='coerce'
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  880A0159BA5275FB 2025-01-16 17:50:49.136 2025-01-16 17:57:00.710 2025-01-16
1  1A5E1E274B2AF0AD 2025-01-31 06:10:41.818 2025-01-31 06:22:09.499 2025-01-31
2  EA9928D3C05B8377 2025-01-09 16:42:50.213 2025-01-09 17:04:12.870 2025-01-09
3  3C42C367750B9292 2025-01-21 16:14:14.398 2025-01-21 16:37:10.458 2025-01-21
4  94D3B0265A7BDE1F 2025-01-30 16:38:18.840 2025-01-30 17:04:08.166 2025-01-30

## Writign CitiBike data to PostgreSQL Database

In [68]:
citibike_df.to_sql(
    name='jersey_city',
    con=engine,
    if_exists='fail',
    index=False,
    chunksize=50_000,
    method='multi'
)

1002704

### Checking Citibike Data

In [69]:
DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [70]:
query = """

SELECT
    *
FROM jersey_city
LIMIT 10;

"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_date
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member,2025-01-16
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member,2025-01-31
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-09
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-21
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-30
5,9F58D1A2D274211B,electric_bike,2025-01-26 12:41:21.306,2025-01-26 12:50:06.079,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-26
6,06E081ED7FFC3B9A,electric_bike,2025-01-14 07:46:19.544,2025-01-14 07:54:25.887,Hilltop,JC019,Morris Canal,JC072,40.731169,-74.057574,40.712419,-74.038526,member,2025-01-14
7,A2933F641B0B4756,electric_bike,2025-01-01 17:28:06.205,2025-01-01 17:35:36.233,Hilltop,JC019,Glenwood Ave,JC094,40.731169,-74.057574,40.727551,-74.071061,member,2025-01-01
8,5A29AAD1161A2DC7,electric_bike,2025-01-13 12:33:51.980,2025-01-13 12:58:04.250,4 St & River St,HB611,Clinton St & Grand St,5303.06,40.740814,-74.027406,40.715595,-73.987030,casual,2025-01-13
9,598F2567309571D5,electric_bike,2025-01-05 19:10:58.189,2025-01-05 19:18:46.106,Dixon Mills,JC076,Pershing Field,JC024,40.721630,-74.049968,40.742677,-74.051789,member,2025-01-05

## Load Weather Data

### Read Weather CSV

In [71]:
weather_df = pd.read_csv(weather_path)
weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,11.0,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9

### Convert Date Column

In [72]:
weather_df['date'] = pd.to_datetime(
    weather_df['date'],
    errors='coerce'
)

weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,11.0,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9

### Write Weather Data to Database

In [73]:
#| echo: True

weather_df.to_sql(
    name='jersey_weather',
    con=engine,
    if_exists='replace',
    index=False
)

365

In [74]:
query = """

SELECT
    *
FROM jersey_weather
LIMIT 10;

"""

pd.read_sql(
    query,
    con=engine
)

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,11.0,3.9,7.4,4.5,4.5,0.00,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.00,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.00,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1
4,2025-01-05,0.4,-3.6,-2.2,0.0,0.0,0.00,19.9
5,2025-01-06,-1.6,-4.5,-2.3,1.7,0.0,1.19,16.7
6,2025-01-07,-3.0,-8.7,-5.2,0.0,0.0,0.00,29.9
7,2025-01-08,-2.5,-6.6,-4.3,0.0,0.0,0.00,25.4
8,2025-01-09,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0
9,2025-01-10,3.3,-3.9,-0.9,0.0,0.0,0.00,22.5

## Load Neighborhood GeoJSON as Spatial Table

### Read GeoJSON with GeoPandas

In [75]:
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [76]:
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

### Inspect Geometry Type

In [77]:
neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

### Write GeoDataFrame to PostGIS

In [78]:
#| echo: true
neighborhood_gdf.to_postgis(
    name='jersey_city_neighborhoods',
    con=engine,
    if_exists='replace',
    index=False
)

### Check Spatial Table

In [79]:
query = """

SELECT
    *
FROM jersey_city_neighborhoods
LIMIT 10;

"""

pd.read_sql(
query,
con=engine
)

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,0103000020E6100000010000002E0300005FD06A586484...
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,0103000020E61000000100000027000000AF9CC1805B84...
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,0103000020E610000001000000840000002697EF6ADD84...
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,0103000020E610000001000000190000001AA825769583...
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,0103000020E6100000010000002000000057337AC7D684...
5,28,411601381.8,9449.068,Journal Square,Mill Creek,NaN,-74.057806,40.722897,0103000020E6100000010000000D000000D6EAD86E8F83...
6,3,411601381.8,9449.068,Heights,Meadowlands,NaN,-74.065425,40.754461,0103000020E61000000100000027010000F0B0993B5583...
7,16,411601381.8,9449.068,Downtown,Metroplaza,26.0,-74.036622,40.723239,0103000020E61000000100000020000000ACBB4A490482...
8,12,411601381.8,9449.068,Downtown,Newport,22.0,-74.034927,40.729255,0103000020E61000000100000071000000F933CEB15F82...
9,50,411601381.8,9449.068,Downtown,Hoboken Yards,22.0,-74.037012,40.734961,0103000020E61000000100000010000000EC8855DB8182...

## Create Station Spatial Table

### Create Station Summary

In [80]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [81]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [82]:
station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [83]:
station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [84]:
station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0

### Convert Station Summary to GeoDataFrame

In [85]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary['lng'],
        station_summary['lat']
    ),
    crs='EPSG:4326'
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0,POINT (-74.0303 40.73594)
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0,POINT (-74.04425 40.7276)
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0,POINT (-74.02901 40.73672)
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0,POINT (-74.03376 40.72722)

### Write Station Points to PostGIS

In [86]:
station_gdf.to_postgis(
    name='jc_2025_stations',
    con=engine,
    if_exists='replace',
    index=False
)

In [87]:
query = """

SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_2025_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,92865.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,52602.0,ST_Point,4326
2,JC009,Hamilton Park,44658.0,ST_Point,4326
3,HB106,River St & Newark St,43602.0,ST_Point,4326
4,JC066,Newport PATH,41402.0,ST_Point,4326

## SQLAlchemy

### List Tables

In [88]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name
0          geography_columns
1           geometry_columns
2                    jc_2025
3           jc_2025_stations
4                jersey_city
5  jersey_city_neighborhoods
6             jersey_weather
7        jersey_weather_2025
8                     people
9            spatial_ref_sys

### Count Rows for each table

In [89]:


query = """
    SELECT 'jc_2025' AS table_name, COUNT(*) AS row_count FROM jc_2025
    UNION ALL
    SELECT 'jersey_weather_2025' AS table_name, COUNT(*) AS row_count FROM jersey_weather_2025
    UNION ALL
    SELECT 'jersey_city_neighborhoods' AS table_name, COUNT(*) AS row_count FROM jersey_city_neighborhoods
    UNION ALL
    SELECT 'jc_2025_stations' AS table_name, COUNT(*) AS row_count FROM jc_2025_stations;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name  row_count
0                    jc_2025    1002704
1        jersey_weather_2025        365
2  jersey_city_neighborhoods         53
3           jc_2025_stations        488

### Daily Ride Volume

In [90]:
query = """
    SELECT
        started_at::date AS ride_date,
        COUNT(*) AS number_of_rides
    FROM jc_2025
    GROUP BY started_at::date
    ORDER BY ride_date;
"""

daily_rides_sql = pd.read_sql(
    query,
    con=engine
)

daily_rides_sql.head()

    ride_date  number_of_rides
0  2024-12-31                2
1  2025-01-01             1179
2  2025-01-02             1711
3  2025-01-03             1771
4  2025-01-04             1337

### Join Citi Bike and Weather

In [91]:
query = """
SELECT
    c.started_at::date AS ride_date,
    COUNT(*) AS number_of_rides,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
FROM jc_2025 AS c
LEFT JOIN jersey_weather_2025 AS w
    ON c.started_at::date = w.date::date
GROUP BY
    c.started_at::date,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
ORDER BY ride_date;
"""

bike_weather_sql = pd.read_sql(
    query,
    con=engine
)

bike_weather_sql.head()

,ride_date,number_of_rides,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2024-12-31,2,NaN,NaN,NaN,NaN,NaN
1,2025-01-01,1179,7.4,4.5,4.5,0.0,23.2
2,2025-01-02,1711,2.6,0.0,0.0,0.0,25.1
3,2025-01-03,1771,0.4,0.0,0.0,0.0,17.1
4,2025-01-04,1337,-1.4,0.0,0.0,0.0,26.1

### Spatial Join in SQL: Stations to Neighborhoods

In [92]:
#| echo: true

query = """
SELECT
    s.station_id,
    s.station_name,
    s.total_departures,
    s.total_arrivals,
    s.total_activity,
    s.net_departures,
    n.neighborhood
FROM jc_2025_stations AS s
JOIN jersey_city_neighborhoods AS n
    ON ST_Within(s.geometry, n.geometry)
ORDER BY s.total_activity DESC;
"""

station_neighborhood_sql = pd.read_sql(
    query,
    con=engine
)

station_neighborhood_sql.head()

,station_id,station_name,total_departures,total_arrivals,total_activity,net_departures,neighborhood
0,JC115,Grove St PATH,45121.0,47744.0,92865.0,-2623.0,Van Vorst Park
1,JC009,Hamilton Park,22311.0,22347.0,44658.0,-36.0,Hamilton Park
2,JC066,Newport PATH,20704.0,20698.0,41402.0,6.0,Newport
3,JC109,Bergen Ave & Sip Ave,20469.0,20357.0,40826.0,112.0,Journal Square
4,JC116,Exchange Pl,20066.0,20144.0,40210.0,-78.0,Exchange Place

### Aggregate Station Activity by Neighborhood in SQL

In [93]:

query = """
SELECT
    n.neighborhood,
    COUNT(DISTINCT s.station_id) AS number_of_stations,
    SUM(s.total_departures) AS total_departures,
    SUM(s.total_arrivals) AS total_arrivals,
    SUM(s.total_activity) AS total_activity,
    SUM(s.net_departures) AS net_departures,
    SUM(s.total_activity)::numeric / NULLIF(COUNT(DISTINCT s.station_id), 0) AS avg_activity_per_station
FROM jersey_city_neighborhoods AS n
LEFT JOIN jc_2025_stations AS s
    ON ST_Within(s.geometry, n.geometry)
GROUP BY n.neighborhood
ORDER BY total_activity DESC;
"""

neighborhood_activity_sql = pd.read_sql(
    query,
    con=engine
)

neighborhood_activity_sql.head()

,neighborhood,number_of_stations,total_departures,total_arrivals,total_activity,net_departures,avg_activity_per_station
0,Liberty State Park,0,NaN,NaN,NaN,NaN,NaN
1,Western Slope,0,NaN,NaN,NaN,NaN,NaN
2,LSP Industrial,0,NaN,NaN,NaN,NaN,NaN
3,Canal Crossing,0,NaN,NaN,NaN,NaN,NaN
4,Country Village,0,NaN,NaN,NaN,NaN,NaN

## Create Spatial Indexes

In [94]:


with engine.begin() as connection:
    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_2025_stations_geom
        ON jc_2025_stations
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jersey_city_neighborhoods_geom
        ON jersey_city_neighborhoods
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_started_at
        ON jc_2025 (started_at);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_weather_date
        ON jersey_weather_2025 (date);
    """))

## SQLAlchemy Core

In [95]:
from sqlalchemy import text

In [96]:
with engine.connect() as connection:
    connection.execute(text("CREATE TABLE IF NOT EXISTS people (name TEXT, age INTEGER)"))
    connection.execute(text("INSERT INTO people (name, age) VALUES ('Mike', 30)"))
    connection.commit() # Important: Changes must be commited to persist [7, 8]

### Defining Tables MetaData

In [97]:
from sqlalchemy import MetaData, Table, Column, Integer, String

meta = MetaData()

people = Table(
    "people", meta,
    Column("id", Integer, primary_key=True),
    Column("name", String, nullable=False),
    Column("age", Integer)
)

In [98]:
meta.create_all(engine)

### Defining Tables with ORM

In [99]:
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String

class Base(DeclarativeBase):
    pass

class Person(Base):
    __tablename__ = "people"
    
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    age: Mapped[int | None]

In [100]:
Base.metadata.create_all(engine)

### CRUD operations

#### Insert Values

In [101]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("DROP TABLE IF EXISTS people;"))

meta.create_all(engine)

#### Select Values

In [102]:
from sqlalchemy import select

with engine.connect() as conn:
    select_statement = select(people).where(people.c.age > 30)
    result = conn.execute(select_statement)
    for row in result.fetchall():
        print(row)

In [103]:
for row in result.fetchall():
    print(row)

#### Update Values

In [104]:
from sqlalchemy import update

with engine.begin() as conn:
    update_statement = people.update().where(people.c.name == "Jane").values(age=50)
    result = conn.execute(update_statement)

In [105]:
with engine.connect() as conn:
    result = conn.execute(select(people).where(people.c.age > 30))
    for row in result.fetchall():
        print(row)

#### Delete Values

In [106]:
from sqlalchemy import delete

with engine.begin() as conn:
    conn.execute(delete(people).where(people.c.name == "Jane"))

In [107]:
with engine.connect() as conn:
    result = conn.execute(select(people))
    for row in result.fetchall():
        print(row)

## Create MV

In [108]:
from sqlalchemy import text

In [109]:
create_tableau_materialized_view_sql = """
DROP MATERIALIZED VIEW IF EXISTS mv_tableau_citibike_dashboard;

CREATE MATERIALIZED VIEW mv_tableau_citibike_dashboard AS
WITH ride_base AS (
    SELECT
        c.ride_id,
        c.rideable_type,
        c.member_casual,

        c.started_at,
        c.ended_at,
        c.started_at::date AS ride_date,

        EXTRACT(YEAR FROM c.started_at)::int AS ride_year,
        EXTRACT(QUARTER FROM c.started_at)::int AS ride_quarter,
        EXTRACT(MONTH FROM c.started_at)::int AS ride_month,
        TO_CHAR(c.started_at, 'Month') AS ride_month_name,
        TO_CHAR(c.started_at, 'Day') AS ride_day_of_week,
        EXTRACT(ISODOW FROM c.started_at)::int AS ride_day_number,
        EXTRACT(HOUR FROM c.started_at)::int AS ride_hour,

        CASE
            WHEN EXTRACT(ISODOW FROM c.started_at) IN (6, 7)
                THEN 'Weekend'
            ELSE 'Weekday'
        END AS weekday_type,

        EXTRACT(EPOCH FROM (c.ended_at - c.started_at)) / 60.0 AS ride_duration_minutes,

        c.start_station_id,
        c.start_station_name,
        c.end_station_id,
        c.end_station_name,

        c.start_lat,
        c.start_lng,
        c.end_lat,
        c.end_lng,

        ST_SetSRID(
            ST_MakePoint(c.start_lng, c.start_lat),
            4326
        ) AS start_geom,

        ST_SetSRID(
            ST_MakePoint(c.end_lng, c.end_lat),
            4326
        ) AS end_geom

    FROM jersey_city AS c
    WHERE
        c.ride_id IS NOT NULL
        AND c.started_at IS NOT NULL
        AND c.ended_at IS NOT NULL
        AND c.ended_at > c.started_at
        AND c.start_lat IS NOT NULL
        AND c.start_lng IS NOT NULL
        AND c.end_lat IS NOT NULL
        AND c.end_lng IS NOT NULL
)

SELECT
    r.ride_id,
    r.rideable_type,
    r.member_casual,

    r.started_at,
    r.ended_at,
    r.ride_date,
    r.ride_year,
    r.ride_quarter,
    r.ride_month,
    TRIM(r.ride_month_name) AS ride_month_name,
    TRIM(r.ride_day_of_week) AS ride_day_of_week,
    r.ride_day_number,
    r.ride_hour,
    r.weekday_type,

    r.ride_duration_minutes,

    r.start_station_id,
    r.start_station_name,
    r.end_station_id,
    r.end_station_name,

    r.start_lat,
    r.start_lng,
    r.end_lat,
    r.end_lng,

    start_n.neighborhood AS start_neighborhood,
    end_n.neighborhood AS end_neighborhood,

    ST_Distance(
        r.start_geom::geography,
        r.end_geom::geography
    ) / 1000.0 AS distance_km,

    CASE
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 1
            THEN 'Short'
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 3
            THEN 'Medium'
        ELSE 'Long'
    END AS distance_group,

    CASE
        WHEN r.ride_duration_minutes < 10
            THEN 'Short'
        WHEN r.ride_duration_minutes < 30
            THEN 'Medium'
        ELSE 'Long'
    END AS duration_group,

    w.temperature_2m_max,
    w.temperature_2m_min,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max,

    CASE
        WHEN w.precipitation_sum > 0
            THEN 'Precipitation'
        ELSE 'No Precipitation'
    END AS precipitation_flag,

    CASE
        WHEN w.temperature_2m_mean < 0
            THEN 'Freezing'
        WHEN w.temperature_2m_mean < 10
            THEN 'Cold'
        WHEN w.temperature_2m_mean < 20
            THEN 'Mild'
        ELSE 'Warm'
    END AS temperature_group

FROM ride_base AS r

LEFT JOIN jersey_weather AS w
    ON r.ride_date = w.date::date

LEFT JOIN jersey_city_neighborhoods AS start_n
    ON ST_Within(r.start_geom, start_n.geometry)

LEFT JOIN jersey_city_neighborhoods AS end_n
    ON ST_Within(r.end_geom, end_n.geometry);
"""

In [110]:
with engine.begin() as connection:
    connection.execute(text(create_tableau_materialized_view_sql))

### Check the Materialized View

In [111]:
query = """
SELECT *
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,member_casual,started_at,ended_at,ride_date,ride_year,ride_quarter,ride_month,ride_month_name,...,duration_group,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,precipitation_flag,temperature_group
0,F70CE58DEEF978B9,electric_bike,casual,2024-12-31 23:47:38.670,2025-01-01 00:14:23.861,2024-12-31,2024,4,12,December,...,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Precipitation,Warm
1,08D9B95649597AD8,classic_bike,member,2025-01-01 11:40:05.004,2025-01-01 11:43:23.618,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
2,7868937D53EF492A,classic_bike,casual,2025-01-01 18:25:59.385,2025-01-01 18:56:17.230,2025-01-01,2025,1,1,January,...,Long,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
3,D090BBA28A63A45E,classic_bike,member,2025-01-01 12:52:53.248,2025-01-01 13:03:25.922,2025-01-01,2025,1,1,January,...,Medium,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
4,4EB3E5265123F007,electric_bike,member,2025-01-01 15:39:22.085,2025-01-01 15:42:27.146,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
5,8683F8C452702B72,electric_bike,member,2025-01-01 19:30:26.190,2025-01-01 19:31:52.723,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
6,10C0ED85E4A788F6,electric_bike,member,2025-01-01 12:59:29.019,2025-01-01 13:04:57.625,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
7,54EF3A868290CFC1,classic_bike,member,2025-01-01 09:30:56.168,2025-01-01 09:40:20.436,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
8,80AF436CF3BC4520,electric_bike,casual,2025-01-01 01:26:18.893,2025-01-01 01:32:51.026,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
9,E647D80F7C27FD74,electric_bike,member,2025-01-01 12:36:03.944,2025-01-01 12:40:22.771,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold

### Check Number of Rows

In [112]:
query = """
SELECT
    COUNT(*) AS number_of_rows
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

   number_of_rows
0          999251

### Check Data Quality

In [113]:
query = """
SELECT
    COUNT(*) AS total_rides,

    COUNT(temperature_2m_mean) AS rides_with_weather,
    COUNT(*) - COUNT(temperature_2m_mean) AS rides_missing_weather,

    COUNT(start_neighborhood) AS rides_with_start_neighborhood,
    COUNT(*) - COUNT(start_neighborhood) AS rides_missing_start_neighborhood,

    COUNT(end_neighborhood) AS rides_with_end_neighborhood,
    COUNT(*) - COUNT(end_neighborhood) AS rides_missing_end_neighborhood,

    COUNT(distance_km) AS rides_with_distance,
    COUNT(*) - COUNT(distance_km) AS rides_missing_distance
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

,total_rides,rides_with_weather,rides_missing_weather,rides_with_start_neighborhood,rides_missing_start_neighborhood,rides_with_end_neighborhood,rides_missing_end_neighborhood,rides_with_distance,rides_missing_distance
0,999251,999249,2,547065,452186,542737,456514,999251,0

### Create Indexes on the Materialized View

In [114]:

with engine.begin() as connection:
    connection.execute(text("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_tableau_ride_id
        ON mv_tableau_citibike_dashboard (ride_id);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_date
        ON mv_tableau_citibike_dashboard (ride_date);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_month
        ON mv_tableau_citibike_dashboard (ride_year, ride_month);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_hour
        ON mv_tableau_citibike_dashboard (ride_hour);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_member_casual
        ON mv_tableau_citibike_dashboard (member_casual);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_rideable_type
        ON mv_tableau_citibike_dashboard (rideable_type);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_station
        ON mv_tableau_citibike_dashboard (start_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_station
        ON mv_tableau_citibike_dashboard (end_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_neighborhood
        ON mv_tableau_citibike_dashboard (start_neighborhood);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_neighborhood
        ON mv_tableau_citibike_dashboard (end_neighborhood);
    """))

### Refresh Materialized View

In [115]:


with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;")
    )

In [116]:
with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;")
    )

### Create Helper Function to Refresh the Dashboard View

In [117]:
def refresh_tableau_dashboard_view(engine, concurrently=False):
    if concurrently:
        refresh_sql = """
        
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;
        
        """
        
    else:
        refresh_sql = """
        
        REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;
        
        """
        
    with engine.begin() as connection:
        connection.execute(text(refresh_sql))

In [119]:
refresh_tableau_dashboard_view(
    engine=engine,
    concurrently=True
)

### Preview Fields for Tableau

In [120]:
query = """
SELECT
    ride_id,
    ride_date,
    ride_month_name,
    ride_day_of_week,
    weekday_type,
    ride_hour,
    rideable_type,
    member_casual,
    start_station_name,
    end_station_name,
    start_neighborhood,
    end_neighborhood,
    ride_duration_minutes,
    duration_group,
    distance_km,
    distance_group,
    temperature_2m_mean,
    temperature_group,
    precipitation_sum,
    precipitation_flag,
    rain_sum,
    snowfall_sum,
    wind_speed_10m_max
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,ride_date,ride_month_name,ride_day_of_week,weekday_type,ride_hour,rideable_type,member_casual,start_station_name,end_station_name,...,duration_group,distance_km,distance_group,temperature_2m_mean,temperature_group,precipitation_sum,precipitation_flag,rain_sum,snowfall_sum,wind_speed_10m_max
0,880A0159BA5275FB,2025-01-16,January,Thursday,Weekday,17,electric_bike,member,Hilltop,Pershing Field,...,Short,1.368211,Medium,-3.2,Freezing,0.3,Precipitation,0.0,0.21,10.7
1,1A5E1E274B2AF0AD,2025-01-31,January,Friday,Weekday,6,electric_bike,member,Hilltop,Jackson Square,...,Medium,2.863311,Medium,3.6,Cold,10.3,Precipitation,10.3,0.00,13.5
2,EA9928D3C05B8377,2025-01-09,January,Thursday,Weekday,16,classic_bike,member,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,...,Medium,2.363587,Medium,-4.2,Freezing,0.0,No Precipitation,0.0,0.00,29.0
3,3C42C367750B9292,2025-01-21,January,Tuesday,Weekday,16,electric_bike,member,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,...,Medium,2.363587,Medium,-11.4,Freezing,0.4,Precipitation,0.0,0.28,10.0
4,94D3B0265A7BDE1F,2025-01-30,January,Thursday,Weekday,16,classic_bike,member,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,...,Medium,2.363587,Medium,-2.0,Freezing,0.0,No Precipitation,0.0,0.00,15.5
5,9F58D1A2D274211B,2025-01-26,January,Sunday,Weekend,12,electric_bike,member,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,...,Short,2.363587,Medium,-1.0,Freezing,0.0,No Precipitation,0.0,0.00,15.9
6,06E081ED7FFC3B9A,2025-01-14,January,Tuesday,Weekday,7,electric_bike,member,Hilltop,Morris Canal,...,Short,2.631611,Medium,-1.7,Freezing,0.0,No Precipitation,0.0,0.00,21.1
7,A2933F641B0B4756,2025-01-01,January,Wednesday,Weekday,17,electric_bike,member,Hilltop,Glenwood Ave,...,Short,1.208112,Medium,7.4,Cold,4.5,Precipitation,4.5,0.00,23.2
8,5A29AAD1161A2DC7,2025-01-13,January,Monday,Weekday,12,electric_bike,casual,4 St & River St,Clinton St & Grand St,...,Medium,4.413380,Long,1.3,Cold,0.0,No Precipitation,0.0,0.00,18.3
9,598F2567309571D5,2025-01-05,January,Sunday,Weekend,19,electric_bike,member,Dixon Mills,Pershing Field,...,Short,2.342298,Medium,-2.2,Freezing,0.0,No Precipitation,0.0,0.00,19.9